- name: Setup Database Server
  hosts: database
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: ["gnupg", "curl"]
        state: present

    - name: Add MongoDB GPG key
      shell: curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
      args:
        creates: /usr/share/keyrings/mongodb-server-7.0.gpg

    - name: Add MongoDB repository
      shell: echo "deb [signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
      args:
        creates: /etc/apt/sources.list.d/mongodb-org-7.0.list

    - name: Update apt package list again
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes


